### ISSUE TITLE
[Import] Shapefile

### ISSUE THREAD

**Issue by fb71** [Polymap4/polymap4-p4#28]
Import of Shapefiles using the new 19: Import framework (http://github.com/Mapzone/mapzone/issues/issue/19)

This is the example for importers that actually 'import' something in the local database.

### To do:

  - [x] charset prompt (*.cpg)
    - [ ] check wrong/unknown charset in *.cpg file (UnsupportedCharsetException, see comment)
  - [x] check/specify **missing** CRS (*.prj)
  - [ ] check if all necessary files are there (?)

**Comment by joergreichert** [comment]
Fehlerfall "ungültiges Encoding in cpg Datei" - momentan wird dann diese Fehlermeldung angezeigt -> reicht das?: 
![crs_invalid](https://cloud.githubusercontent.com/assets/994131/11063291/cda3fc4a-87b5-11e5-96b4-a31aa96bda4c.png)

!ENTRY org.polymap.core 2 0 2015-11-10 14:14:54.286
!MESSAGE UTV-8
!STACK 0
java.nio.charset.UnsupportedCharsetException: UTV-8
	at java.nio.charset.Charset.forName(Charset.java:531)
	at org.polymap.p4.data.imports.shapefile.CharsetPrompt.<init>(CharsetPrompt.java:57)
	at org.polymap.p4.data.imports.shapefile.ShpImporter.createPrompts(ShpImporter.java:90)
	at org.polymap.p4.data.imports.ImporterContext.lambda$3(ImporterContext.java:154)
	at org.polymap.core.runtime.SubMonitor.complete(SubMonitor.java:82)
	at org.polymap.p4.data.imports.ImporterContext.<init>(ImporterContext.java:154)
	at org.polymap.p4.data.imports.ImporterContext$4.newImporter(ImporterContext.java:238)
	at org.polymap.p4.data.imports.shapefile.ShpImporterFactory.createImporters(ShpImporterFactory.java:53)
	at org.polymap.p4.data.imports.ImporterContext.findNext(ImporterContext.java:235)
	at org.polymap.p4.data.imports.ImportsContentProvider$1.runWithException(ImportsContentProvider.java:148)
	at org.polymap.core.runtime.UIJob.lambda$1(UIJob.java:182)
	at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:67)
	at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:41)
	at org.eclipse.rap.rwt.lifecycle.UICallBack.runNonUIThreadWithFakeContext(UICallBack.java:54)
	at org.polymap.core.runtime.session.RapSessionContextProvider$RapSessionContext.execute(RapSessionContextProvider.java:132)
	at org.polymap.core.runtime.UIJob.run(UIJob.java:178)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by fb71** [comment]
I add this to issue description. Thanks! :)
