### ISSUE TITLE
[Import] Exception on duplicate schema name

### ISSUE THREAD

**Issue by stundzig** [Polymap4/polymap4-p4#68]
If i import a file twice, then after clikc at *import* i got an errormessage:
````
[WARN]  StatusDispatcher       : Die Aktion "Import features" hat ein Problem festgestellt und musste erfolglos abgebrochen werden.
org.eclipse.core.commands.ExecutionException: Schema name already exists: Stakeholder kurz
	at org.polymap.core.operation.DefaultOperation.handleException(DefaultOperation.java:60)
	at org.polymap.core.operation.DefaultOperation.execute(DefaultOperation.java:66)
	at org.polymap.p4.data.imports.features.AddLayerForImportedFeaturesConcern$AddLayerOperationConcern.execute(AddLayerForImportedFeaturesConcern.java:95)
	at org.polymap.core.operation.LogOperationConcernFactory$1.execute(LogOperationConcernFactory.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.polymap.core.operation.OperationExecutor.invoke(OperationExecutor.java:113)
	at com.sun.proxy.$Proxy28.execute(Unknown Source)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:513)
	at org.polymap.core.operation.OperationSupport$5.run(OperationSupport.java:271)
	at org.polymap.core.operation.OperationSupport$OperationJob.runWithException(OperationSupport.java:340)
	at org.polymap.core.runtime.UIJob.lambda$1(UIJob.java:182)
	at org.polymap.core.runtime.UIJob$$Lambda$78/2138506683.run(Unknown Source)
	at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:67)
	at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:41)
	at org.eclipse.rap.rwt.lifecycle.UICallBack.runNonUIThreadWithFakeContext(UICallBack.java:54)
	at org.polymap.core.runtime.session.RapSessionContextProvider$RapSessionContext.execute(RapSessionContextProvider.java:132)
	at org.polymap.core.runtime.UIJob.run(UIJob.java:178)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.io.IOException: Schema name already exists: Stakeholder kurz
	at org.polymap.core.data.rs.RDataStore.createSchema(RDataStore.java:207)
	at org.polymap.p4.data.imports.features.ImportFeaturesOperation.doExecute(ImportFeaturesOperation.java:93)
	at org.polymap.core.operation.DefaultOperation.lambda$0(DefaultOperation.java:66)
	at org.polymap.core.operation.DefaultOperation$$Lambda$185/1489227453.call(Unknown Source)
	at org.polymap.core.operation.DefaultOperation.handleException(DefaultOperation.java:54)
	... 20 more
```
But here it would be better to show a dialog to the customer to change the name or create a new name automatically e.g. with numbering.

**Comment by stundzig** [comment]
This issue should be solve with the new schemaNamePrompt. If the schema always exists, then the user must select another name. This name is also used for the layer.

**Comment by fb71** [comment]
Is the new schemaNamePrompt used by all importers?

**Comment by stundzig** [comment]
no, the shapefileimporter doesnt use it
