### ISSUE TITLE
Feature edit: After save an completely different item is displayed in form

### ISSUE THREAD

**Issue by joergreichert** [Polymap4/polymap4-p4#69]
How to to reproduce:
1. Import data
2. Do not sort data yet in feature table
3. Click on first item in table to edit
4. change a value of that item and hit save

SHOULD: just changed item should be displayed in form
IS: completely different item is loaded in form

Some notes:
 * When looking for the changed item inside the table, it can be found and the changes were also persisted.
 * When sorting the table in step two, then it works, i.e. the changed item is loaded again inside the form
 * When saving (without sorting before) the following exception occured:

!ENTRY org.eclipse.rap.jface 4 2 2016-01-28 10:43:56.735
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.rap.jface".
!STACK 0
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.polymap.p4.layer.FeatureSelectionTable.lambda$0(FeatureSelectionTable.java:140)
	at org.eclipse.jface.viewers.Viewer$2.run(Viewer.java:166)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:52)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:177)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:164)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2172)
	at org.eclipse.jface.viewers.StructuredViewer.handleInvalidSelection(StructuredViewer.java:1159)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1440)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1388)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1490)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:537)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1449)
	at org.polymap.rhei.table.FeatureTableViewer.refresh(FeatureTableViewer.java:200)
	at org.polymap.p4.layer.FeatureSelectionTable.onFeatureChange(FeatureSelectionTable.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.polymap.core.runtime.event.AnnotatedEventListener$AnnotatedMethod.handleEvent(AnnotatedEventListener.java:198)
	at org.polymap.core.runtime.event.DisplayingListener$1.run(DisplayingListener.java:58)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:180)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1196)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.polymap.rhei.batik.BatikApplication.createUI(BatikApplication.java:122)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:172)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:284)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:105)
[INFO]  PanelStatusHandler     : Problems occurred when invoking code from plug-in: "org.eclipse.rap.jface".
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.polymap.p4.layer.FeatureSelectionTable.lambda$0(FeatureSelectionTable.java:140)
	at org.eclipse.jface.viewers.Viewer$2.run(Viewer.java:166)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:52)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:177)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:164)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2172)
	at org.eclipse.jface.viewers.StructuredViewer.handleInvalidSelection(StructuredViewer.java:1159)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1440)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1388)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1490)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:537)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1449)
	at org.polymap.rhei.table.FeatureTableViewer.refresh(FeatureTableViewer.java:200)
	at org.polymap.p4.layer.FeatureSelectionTable.onFeatureChange(FeatureSelectionTable.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.polymap.core.runtime.event.AnnotatedEventListener$AnnotatedMethod.handleEvent(AnnotatedEventListener.java:198)
	at org.polymap.core.runtime.event.DisplayingListener$1.run(DisplayingListener.java:58)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:180)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1196)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.polymap.rhei.batik.BatikApplication.createUI(BatikApplication.java:122)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:172)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:284)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:105)
[INFO]  PanelStatusHandler     : An error has occurred. See error log for more details.
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.polymap.p4.layer.FeatureSelectionTable.lambda$0(FeatureSelectionTable.java:140)
	at org.eclipse.jface.viewers.Viewer$2.run(Viewer.java:166)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:52)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:177)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:164)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2172)
	at org.eclipse.jface.viewers.StructuredViewer.handleInvalidSelection(StructuredViewer.java:1159)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1440)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1388)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1490)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:537)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1449)
	at org.polymap.rhei.table.FeatureTableViewer.refresh(FeatureTableViewer.java:200)
	at org.polymap.p4.layer.FeatureSelectionTable.onFeatureChange(FeatureSelectionTable.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.polymap.core.runtime.event.AnnotatedEventListener$AnnotatedMethod.handleEvent(AnnotatedEventListener.java:198)
	at org.polymap.core.runtime.event.DisplayingListener$1.run(DisplayingListener.java:58)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:180)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1196)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.polymap.rhei.batik.BatikApplication.createUI(BatikApplication.java:122)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:172)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:284)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:105)
[WARN]  BatikPlugin            : An error has occurred. See error log for more details.
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at org.polymap.p4.layer.FeatureSelectionTable.lambda$0(FeatureSelectionTable.java:140)
	at org.eclipse.jface.viewers.Viewer$2.run(Viewer.java:166)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:52)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:177)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:164)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2172)
	at org.eclipse.jface.viewers.StructuredViewer.handleInvalidSelection(StructuredViewer.java:1159)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1440)
	at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1388)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1490)
	at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:537)
	at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1449)
	at org.polymap.rhei.table.FeatureTableViewer.refresh(FeatureTableViewer.java:200)
	at org.polymap.p4.layer.FeatureSelectionTable.onFeatureChange(FeatureSelectionTable.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.polymap.core.runtime.event.AnnotatedEventListener$AnnotatedMethod.handleEvent(AnnotatedEventListener.java:198)
	at org.polymap.core.runtime.event.DisplayingListener$1.run(DisplayingListener.java:58)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:180)
	at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1196)
	at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
	at org.polymap.rhei.batik.BatikApplication.createUI(BatikApplication.java:122)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:172)
	at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:284)
	at java.lang.Thread.run(Thread.java:745)
	at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:105)

**Comment by fb71** [comment]
Committing modification via UnitOfWork causes FeatureEvent, which cauases the entire FeatureTable to refresh, which tries to prevent current selection/index(!). With no sorting the sequence of features in the table is undefined, so the preserved selection index selects a new feature. This is fexid by setting first column as default sort. However, if attribute of the currently sorted column is modified, this will happen again. Using a different content provider for the FeatureTable is the only way to fix this.
